# Generated by Django 5.1.15 on 2026-03-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
